#!/bin/bash
printf "LOGIN / UID / PATH\n"
cat /etc/passwd | egrep -v "(^#.*|^$)" | awk -F ':' '{print $1, $3, $6}'

# egrep -v "(^#.*|^$)" : filters out the comments
# awk -F : seperate by ':' and print the 1,3,6 item.
